### ISSUE TITLE
"This plugin is not available as a Gem." -> ??

### ISSUE THREAD

**Issue by mfowlewebs** [FundingCircle/fluent-plugin-graylog#12]
Um, why is this plugin not available as a Gem?

**Comment by timstott** [comment]
Good point @mfowlewebs. I will check with @FundingCircle/owners

**Comment by sgerrand** [comment]
:tada: @mfowlewebs: This gem has been [published to RubyGems](https://rubygems.org/gems/fluent-plugin-graylog). The installation instructions are updated in #13.
